name: Hello Template

on:
  workflow_call:
    inputs:
      username:
        description: "Nom de la personne à saluer"
        required: true
        type: string

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Dire bonjour
        run: echo "Bonjour ${{ inputs.username }} depuis le workflow réutilisable !"